export { CommonModule } from '@angular/common';
export {
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
  OnInit,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
export { FormsModule } from '@angular/forms';
export { RouterLink } from '@angular/router';
export { MatButtonModule } from '@angular/material/button';
export { MatFormFieldModule } from '@angular/material/form-field';
export { MatSelectModule } from '@angular/material/select';
export { MatInputModule } from '@angular/material/input';
export { MatSnackBar } from '@angular/material/snack-bar';
export { MatDialog, MatDialogModule } from '@angular/material/dialog';
export { HttpClient } from '@angular/common/http';
export { Observable, catchError, concatMap, defaultIfEmpty, finalize, forkJoin, from, map, mergeMap, of, switchMap, take, timeout, toArray } from 'rxjs';
export { CareerService } from '../../../core/services/career.service';
export { AppLoggerService } from '../../../core/services/app-logger.service';
export { Fixture } from '../../../core/services/career.model';
export { environment } from '../../../environments/environment';
export { MatchDetailApiService } from '../../match-detail/services/match-detail-api.service';
export { MatchDetail, MatchEvent, TimelineSnapshot } from '../../match-detail/models/match-detail.model';
export { V24MatchDetailPageComponent } from '../../match-detail/pages/v24-match-detail-page.component';
export { SquadEditorModalComponent } from '../../../components/squad-editor-modal/squad-editor-modal.component';
export { SessionPlayer } from '../../../shared/models/player.model';
export { LineupDTO } from '../../../shared/models/lineup/lineup.dto';
export { LineupSlotDTO } from '../../../shared/models/lineup/lineup-slot.dto';
export { FormationDTO } from '../../../shared/models/lineup/formation.dto';
export {
  FORMATION_CODES,
  AllFormationRoleSlotSmokeRow,
  BackFiveContextSmokeRow,
  BackFiveContextSmokeSummary,
  BackFiveFamilyLabRow,
  BackFiveTransitionLabRow,
  ControlledTeamSide,
  CustomFixture,
  CurrentLineupReplaySample,
  CurrentLineupMultiSeedSummary,
  CurrentLineupReplayResult,
  FocusedWideBatteryRow,
  FormationCoachPick,
  FormationCoachSummary,
  FormationCode,
  FormationLineSmokeRow,
  FormationMatrixRow,
  FormationMatrixSummaryRow,
  FormationReplayResult,
  LabMutationResult,
  LastModalPositionMoveCase,
  LineupDebugRow,
  LineupDebugSnapshot,
  LineupDiagnostic,
  LineupDiagnosticPlayer,
  LineupDiagnosticTeam,
  LowBlockLabRow,
  MatchFixture,
  MatchPreviewSummary,
  ModalVsCanonicalSummary,
  ModalRecommendationCandidateAttempt,
  PlayerSwapBatterySummary,
  PlayerSwapBenchOption,
  PlayerSwapCandidate,
  PlayerSwapMatrixSummaryRow,
  PlayerSwapMatrixSummary,
  PlayerSwapPrecisionComparisonRow,
  PlayerSwapSlotOption,
  PositionPixelQaLine,
  PositionPixelQaSummaryRow,
  PositionPixelCandidate,
  PositionPixelDiagonalSummary,
  PositionPixelExportRow,
  PositionPixelLineBreakSummary,
  PositionPixelReadFilter,
  PositionPixelReadLevel,
  PositionPixelMatrixSummaryRow,
  PositionPixelMatrixSummary,
  PositionPixelMatchSmokeSummary,
  PositionPixelPlayerSmokeSummary,
  PositionPixelSmokeRunSummary,
  PositionPixelSmokeScope,
  PositionPixelSortMode,
  ProfessionalQaActionStatus,
  ProfessionalQaChecklistRow,
  ProfessionalSmokeSummary,
  RoleSlotImpactSmokeRow,
  RoleSlotImpactSummaryRow,
  RoundGroup,
  ScenarioBatteryCoachObjective,
  ScenarioBatteryCoachObjectiveModel,
  ScenarioBatteryCoachAdvice,
  ScenarioBatteryReviewItem,
  ScenarioBatteryRow,
  ScenarioDecisionCard,
  ScenarioMatrixRow,
  ScenarioMatrixSummaryRow,
  ScenarioScoutingNote,
  ScenarioSummaryReadFilter,
  ScenarioSummaryReadLevel,
  ScenarioSummarySortMode,
  SideMirrorDecisionRow,
  SideMirrorDecisionSummary,
  SideMirrorSmokeRow,
  SideMirrorSmokeSummary,
  SideMirrorSyntheticLabRow,
  SubstitutionWhatIfSummaryRow,
  SubstitutionWhatIfSummary,
  SubstitutionTimingMatrixRow,
  TestHarnessMatchRow,
  TestHarnessSquadHealthSummary,
  TestHarnessSnapshotFixture,
  TestHarnessSnapshotResponse,
  TeamStyle,
  FormationWidthRead,
  FormationWingbackRead,
  WingbackLabRow,
} from '../models/test-harness.model';
export { TestHarnessService } from '../services/test-harness.service';
export {
  CURRENT_LINEUP_MULTI_SEED_COUNT,
  CURRENT_LINEUP_MULTI_SEED_TIMEOUT_MS,
  DEFAULT_REPLAY_SEED,
  SINGLE_MATCH_REPLAY_TIMEOUT_MS,
  TEST_HARNESS_MINUTE_TICKS,
  TIMELINE_DEBOUNCE_MS,
  TIMELINE_MAX_MINUTE,
  TIMELINE_STEP,
} from './test-harness.constants';
export {
  AUTO_PLAYER_SWAP_BENCH,
  AUTO_PLAYER_SWAP_STARTER,
  ROLE_SLOT_IMPACT_SLOT_OPTIONS,
  SUBSTITUTION_WHAT_IF_MINUTE_OPTIONS,
  TEAM_STYLE_OPTIONS,
} from './test-harness-page.options';
export {
  csvCell as formatCsvCell,
  csvLines as buildCsvLines,
  downloadTextFile as saveTextFile,
  playerSwapMatrixExportRow,
} from './test-harness-export-utils';
export {
  deltaClassName,
  formatDeltaInt,
  formatDeltaMicro,
  formatDeltaNumber,
  formatPercent,
  formatXg,
} from './test-harness-format-utils';
export {
  professionalQaActionLabel as getProfessionalQaActionLabel,
  professionalQaActionStatusClass as getProfessionalQaActionStatusClass,
  professionalQaCheckLabel as getProfessionalQaCheckLabel,
  professionalQaChecklistTestId as getProfessionalQaChecklistTestId,
  professionalQaTextLabel as getProfessionalQaTextLabel,
  professionalQaVerdictClass as getProfessionalQaVerdictClass,
  professionalQaVerdictLabel as getProfessionalQaVerdictLabel,
  professionalSmokeVerdictClass as getProfessionalSmokeVerdictClass,
} from './test-harness-professional-qa-utils';
export {
  buildScenarioBatteryRow as buildScenarioBatteryRowUtils,
  buildScenarioDecisionCardsFromSummary as buildScenarioDecisionCardsFromSummaryUtils,
  inferScenarioBatteryCoachObjective as inferScenarioBatteryCoachObjectiveUtils,
  scenarioActionLabel as getScenarioActionLabel,
  scenarioActionKey as getScenarioActionKey,
  scenarioAttackCandidateIsCoachWorthy as getScenarioAttackCandidateIsCoachWorthy,
  scenarioAttackPlanScore as getScenarioAttackPlanScore,
  scenarioBatteryCardDetail as getScenarioBatteryCardDetail,
  scenarioBatteryCardSummary as getScenarioBatteryCardSummary,
  scenarioBatteryCandidateMatches as getScenarioBatteryCandidateMatches,
  scenarioBatteryAutoObjectiveHint as getScenarioBatteryAutoObjectiveHint,
  scenarioBatteryCoachContext as getScenarioBatteryCoachContext,
  scenarioBatteryCoachAdvice as getScenarioBatteryCoachAdvice,
  scenarioBatteryCoachObjectiveHint as getScenarioBatteryCoachObjectiveHint,
  scenarioBatteryDecision as getScenarioBatteryDecision,
  scenarioBatteryDecisionMinute as getScenarioBatteryDecisionMinute,
  scenarioBatteryDecisionReview as getScenarioBatteryDecisionReview,
  scenarioBatteryCoachObjectiveLabel as getScenarioBatteryCoachObjectiveLabel,
  scenarioBatteryExportRow as getScenarioBatteryExportRow,
  scenarioBatteryCoverageHint as getScenarioBatteryCoverageHint,
  scenarioBatteryContextPressure as getScenarioBatteryContextPressure,
  scenarioBatteryGroupHint as getScenarioBatteryGroupHint,
  scenarioBatteryGroupLabel as getScenarioBatteryGroupLabel,
  scenarioBatteryGoalDiff as getScenarioBatteryGoalDiff,
  scenarioBatteryMatchStateText as getScenarioBatteryMatchStateText,
  scenarioBatteryMetricText as getScenarioBatteryMetricText,
  scenarioBatteryReviewCount as getScenarioBatteryReviewCount,
  scenarioBatteryReviewHint as getScenarioBatteryReviewHint,
  scenarioBatteryReviewItems as getScenarioBatteryReviewItems,
  scenarioBatteryRiskCardDetail as getScenarioBatteryRiskCardDetail,
  scenarioBatteryRiskCardSummary as getScenarioBatteryRiskCardSummary,
  scenarioBatteryProgressText as getScenarioBatteryProgressText,
  scenarioBatteryScenarioCountEstimate as getScenarioBatteryScenarioCountEstimate,
  scenarioBatteryScopeHint as getScenarioBatteryScopeHint,
  scenarioBatterySquadText as getScenarioBatterySquadText,
  scenarioBatteryTeamCondition as getScenarioBatteryTeamCondition,
  scenarioBatteryTeamRating as getScenarioBatteryTeamRating,
  scenarioBatteryTeamReputation as getScenarioBatteryTeamReputation,
  scenarioDecisionMetrics as getScenarioDecisionMetrics,
  scenarioOpponentProtectionRead as getScenarioOpponentProtectionRead,
  scenarioOpponentRiskRead as getScenarioOpponentRiskRead,
  scenarioProtectionCandidateIsCoachWorthy as getScenarioProtectionCandidateIsCoachWorthy,
  scenarioShapeActionLabel as getScenarioShapeActionLabel,
  scenarioSummaryActionLabel as getScenarioSummaryActionLabel,
  scenarioSummaryAttackGainScore as getScenarioSummaryAttackGainScore,
  scenarioSummaryAttackLossScore as getScenarioSummaryAttackLossScore,
  scenarioSummaryCoachRead as getScenarioSummaryCoachRead,
  scenarioSummaryCoachReadDetail as getScenarioSummaryCoachReadDetail,
  scenarioSummaryCoachReadPrefix as getScenarioSummaryCoachReadPrefix,
  scenarioSummaryCoherentSubstitutionSignal as getScenarioSummaryCoherentSubstitutionSignal,
  scenarioDecisionConfidenceFromReadLevel as getScenarioDecisionConfidenceFromReadLevel,
  scenarioSummaryDefensiveGainScore as getScenarioSummaryDefensiveGainScore,
  scenarioSummaryDefensiveRiskScore as getScenarioSummaryDefensiveRiskScore,
  scenarioSummaryFormationHint as getScenarioSummaryFormationHint,
  scenarioSummaryFormationLabel as getScenarioSummaryFormationLabel,
  scenarioSummaryImpactScore as getScenarioSummaryImpactScore,
  scenarioSummaryIsFormationNoop as getScenarioSummaryIsFormationNoop,
  scenarioSummaryNeedsReview as getScenarioSummaryNeedsReview,
  scenarioSummaryIsOpponentRow as getScenarioSummaryIsOpponentRow,
  scenarioSummaryIsShapeAction as getScenarioSummaryIsShapeAction,
  scenarioSummaryOpponentChannelRead as getScenarioSummaryOpponentChannelRead,
  scenarioSummaryOutcome as getScenarioSummaryOutcome,
  scenarioSummaryOutcomeClass as getScenarioSummaryOutcomeClass,
  scenarioSummaryOutcomeReason as getScenarioSummaryOutcomeReason,
  scenarioSummaryOutcomeSummaryFromOutcomes as getScenarioSummaryOutcomeSummaryFromOutcomes,
  scenarioSummaryRecommendationClass as getScenarioSummaryRecommendationClass,
  scenarioSummaryRecommendationDetail as getScenarioSummaryRecommendationDetail,
  scenarioSummaryRecommendationFromOutcome as getScenarioSummaryRecommendationFromOutcome,
  scenarioSummaryUserChannelRead as getScenarioSummaryUserChannelRead,
  scenarioTwoWayScore as getScenarioTwoWayScore,
  styleLabelFromActionDetail as getStyleLabelFromActionDetail,
} from './test-harness-scenario-battery-utils';
export {
  buildSideMirrorSmokeRowsFromMatrix as buildSideMirrorSmokeRowsFromMatrixUtils,
  formationWidthReadFromPositions as getFormationWidthReadFromPositions,
  formationWingbackReadFromPositions as getFormationWingbackReadFromPositions,
  mapSyntheticSideMirrorRows as mapSyntheticSideMirrorRowsUtils,
  sideMirrorRealRead as getSideMirrorRealRead,
} from './side-mirror-read-utils';
export {
  allFormationsRoleSlotSmokeMarkdownReport as buildAllFormationsRoleSlotSmokeMarkdownReport,
  allFormationsRoleSlotSmokeVerdictCounter as countAllFormationsRoleSlotSmokeVerdicts,
  roleSlotImpactSmokeMarkdownReport as buildRoleSlotImpactSmokeMarkdownReport,
  roleSlotImpactSmokeVerdictCounter as countRoleSlotImpactSmokeVerdicts,
} from './role-slot-smoke-report-utils';
export {
  backFiveContextClass as getBackFiveContextClass,
  backFiveContextRead as getBackFiveContextRead,
  backFiveFamilyClass as getBackFiveFamilyClass,
  backFiveFamilyRead as getBackFiveFamilyRead,
  backFiveTransitionClass as getBackFiveTransitionClass,
  backFiveTransitionRead as getBackFiveTransitionRead,
  lowBlockLabClass as getLowBlockLabClass,
  lowBlockLabRead as getLowBlockLabRead,
} from './tactical-lab-read-utils';
export {
  playerSwapHasLargeQualityDrop as hasLargePlayerSwapQualityDrop,
  playerSwapBatteryCoachRead as getPlayerSwapBatteryCoachRead,
  playerSwapBatteryCounterText as getPlayerSwapBatteryCounterText,
  playerSwapBatteryBestWorstText as getPlayerSwapBatteryBestWorstText,
  playerSwapObjectiveContrastText as getPlayerSwapObjectiveContrastText,
  playerSwapObjectiveText as getPlayerSwapObjectiveText,
  playerSwapOverallDelta as getPlayerSwapOverallDelta,
  playerSwapOverallDeltaText as getPlayerSwapOverallDeltaText,
  playerSwapQualityWarning as getPlayerSwapQualityWarning,
  playerSwapCoachAttackScore as getPlayerSwapCoachAttackScore,
  playerSwapCoachNetScore as getPlayerSwapCoachNetScore,
  playerSwapCoachRead as getPlayerSwapCoachRead,
  playerSwapCoachReadClass as getPlayerSwapCoachReadClass,
  playerSwapCoachReadDetail as getPlayerSwapCoachReadDetail,
  playerSwapCoachReadLevel as getPlayerSwapCoachReadLevel,
  playerSwapCoachRiskScore as getPlayerSwapCoachRiskScore,
  playerSwapDecisionScore as getPlayerSwapDecisionScore,
  playerSwapIsActionableRecommendation as getPlayerSwapIsActionableRecommendation,
  playerSwapProtectSpecialistScore as getPlayerSwapProtectSpecialistScore,
  playerSwapPrecisionStability as getPlayerSwapPrecisionStability,
  playerSwapPrecisionStabilityClass as getPlayerSwapPrecisionStabilityClass,
  playerSwapRoleTradeoff as getPlayerSwapRoleTradeoff,
  playerSwapSignalClass as getPlayerSwapSignalClass,
  playerSwapSignalRead as getPlayerSwapSignalRead,
  playerSwapSignalScore as getPlayerSwapSignalScore,
  playerSwapTacticalBreakdown as getPlayerSwapTacticalBreakdown,
  playerSwapTacticalLabel as getPlayerSwapTacticalLabel,
} from './player-swap-analysis';
export {
  playerSwapFitClass as getPlayerSwapFitClass,
  playerSwapFitDetail as getPlayerSwapFitDetail,
  playerSwapFitLevel as getPlayerSwapFitLevel,
  playerSwapFitText as getPlayerSwapFitText,
  playerSwapProfile as getPlayerSwapProfile,
  playerSwapRoleRisk as getPlayerSwapRoleRisk,
} from './player-swap-fit-utils';
export {
  positionPixelAttackGainScore as getPositionPixelAttackGainScore,
  positionPixelAttackLossScore as getPositionPixelAttackLossScore,
  positionPixelChannelBreakdown as getPositionPixelChannelBreakdown,
  positionPixelChannelBreakdownClass as getPositionPixelChannelBreakdownClass,
  positionPixelChannelBreakdownDetail as getPositionPixelChannelBreakdownDetail,
  positionPixelChannelBreakdownRead as getPositionPixelChannelBreakdownRead,
  PositionPixelChannelBreakdown,
  positionPixelChannelSign as getPositionPixelChannelSign,
  positionPixelCoachRead as getPositionPixelCoachRead,
  positionPixelContextualCoverageNote as getPositionPixelContextualCoverageNote,
  positionPixelCoverageChannelLabel as getPositionPixelCoverageChannelLabel,
  positionPixelDecisionScore as getPositionPixelDecisionScore,
  positionPixelDefensiveGainScore as getPositionPixelDefensiveGainScore,
  positionPixelDefensiveRiskScore as getPositionPixelDefensiveRiskScore,
  positionPixelDistance as getPositionPixelDistance,
  positionPixelImpactScore as getPositionPixelImpactScore,
  positionPixelMovementConfidence as getPositionPixelMovementConfidence,
  positionPixelMatchSmokeVerdict as getPositionPixelMatchSmokeVerdict,
  positionPixelPlayerSmokeSeverity as getPositionPixelPlayerSmokeSeverity,
  positionPixelPlayerSmokeVerdict as getPositionPixelPlayerSmokeVerdict,
  positionPixelReadLevel as getPositionPixelReadLevel,
  positionPixelReadSeverity as getPositionPixelReadSeverity,
  positionPixelSignalClass as getPositionPixelSignalClass,
  positionPixelSignalDetail as getPositionPixelSignalDetail,
  positionPixelSignalRead as getPositionPixelSignalRead,
  positionPixelSignalScore as getPositionPixelSignalScore,
  positionPixelSmokeVerdictClass as getPositionPixelSmokeVerdictClass,
  positionPixelChannelLabel as getPositionPixelChannelLabel,
  positionPixelShapeDeltaText as getPositionPixelShapeDeltaText,
  positionPixelShapeMove as getPositionPixelShapeMove,
  positionPixelShapeMoveDetail as getPositionPixelShapeMoveDetail,
  positionPixelTacticalRead as getPositionPixelTacticalRead,
  positionPixelTacticalReadClass as getPositionPixelTacticalReadClass,
  positionPixelTacticalReadReason as getPositionPixelTacticalReadReason,
  positionPixelUsesContextualCoverage as getPositionPixelUsesContextualCoverage,
  positionPixelVisualExpectationClass as getPositionPixelVisualExpectationClass,
  positionPixelVisualExpectationDetail as getPositionPixelVisualExpectationDetail,
  positionPixelVisualExpectationMismatches as getPositionPixelVisualExpectationMismatches,
  positionPixelVisualExpectationRead as getPositionPixelVisualExpectationRead,
  positionPixelVisualEngineTensionClass as getPositionPixelVisualEngineTensionClass,
  positionPixelVisualEngineTensionDetail as getPositionPixelVisualEngineTensionDetail,
  positionPixelVisualEngineTensionRead as getPositionPixelVisualEngineTensionRead,
  positionPixelVisualEngineTensions as getPositionPixelVisualEngineTensions,
  PositionPixelVisualEngineTension,
  positionPixelIsMicroVisualMismatch as getPositionPixelIsMicroVisualMismatch,
  positionPixelVisualChannel as getPositionPixelVisualChannel,
  PositionPixelVisualChannel,
  positionPixelVisualLine as getPositionPixelVisualLine,
  PositionPixelVisualLine,
  positionPixelWideChannelReason as getPositionPixelWideChannelReason,
  clampFieldPercent,
  parseFieldSubdivision,
  subdivisionXPercent,
  subdivisionYPercent,
} from './position-pixel-analysis';
export {
  manualExtremeMovementPresets as buildManualExtremeMovementPresets,
  manualShapeVsPresetPresets as buildManualShapeVsPresetPresets,
  positionMicroMovementPresets as buildPositionMicroMovementPresets,
  positionMovementPresets as buildPositionMovementPresets,
  wingbackMovementPresets as buildWingbackMovementPresets,
  wingbackSlotSide as getWingbackSlotSide,
} from './position-movement-presets';
export {
  buildLineupSlots as buildLineupSlotsFromLineup,
  canonicalXPercent as getCanonicalXPercent,
  canonicalYPercent as getCanonicalYPercent,
  countCustomMovableSlots as countCustomMovableLineupSlots,
  fallbackYForPosition as getFallbackYForPosition,
  isAttackingPosition as isAttackingPlayerPosition,
  lineupPlayerIdsFromSlots as getLineupPlayerIdsFromSlots,
  matchContextXPercent as getMatchContextXPercent,
  matchContextYPercent as getMatchContextYPercent,
  positionPixelLine as getPositionPixelLine,
  strictPositionPixelLine as getStrictPositionPixelLine,
  swapLineupSlot as swapLineupSlotPlayer,
} from './lineup-position-utils';
export {
  currentLineupSampleMetrics as buildCurrentLineupSampleMetrics,
  isShotLikeEvent as checkShotLikeEvent,
  summarizeShotZones as summarizeMatchShotZones,
} from './match-sample-metrics-utils';
/**
 * Debug page for replaying and comparing match-engine scenarios.
 */

